import { Chairs } from '../interfaces/chairs-interface';

export const chairs: Chairs[] = [
  {
    category: 'chair',
    name: 'Projek',
    fullName: 'Projek office chair',
    productInfo:
      'Projek is smart, simple seating designed for today’s workplace where shared workspaces are increasingly common. Projek has a clean and unassuming look that allows for visual fit in varied office settings. The chair’s ease and range of adjustment will also fit the great majority of people in a dynamic and diverse workplace.',
    img: 'https://i.ibb.co/Bgwzxq5/IMG-7127.jpg',
    price: 159,
    width: 500,
    height: 550,
    weight: 130,
    type: 'Work',
    feature: ['Armrest', 'Swivel', 'Back'],
    color: ['Beige'],
  },
  {
    category: 'chair',
    name: 'Halmar',
    fullName: 'Mid-century swivel office chair - wood legs',
    productInfo:
      'With its wide swivel seat and sloping back, our Mid-Century Office Chair is comfortable enough for long work days, while remaining entirely easy on the eyes. Go ahead, pull up a seat.',
    img: 'https://i.ibb.co/RcpRL6y/IMG-7128.jpg',
    price: 399,
    width: 480,
    height: 485,
    weight: 110,
    type: 'Work',
    feature: ['Swivel', 'Back'],
    color: ['Beige'],
  },
  {
    category: 'chair',
    name: 'Acme',
    fullName: 'Acme home & office chair',
    productInfo:
      "The Harith office chair brings comfort and style to any work space. Handsome, channel-seamed retro top grain leather upholstery is complemented by a metal base with casters and metal frame armrests. It's Industrial design promise comfort and function as well as stylish style. Some Assembly Required.",
    img: 'https://i.ibb.co/nPCbq7b/IMG-7129.jpg',
    price: 574,
    width: 660,
    height: 560,
    weight: 140,
    type: 'Work',
    feature: ['Armrest', 'Swivel', 'Tilting', 'Back'],
    color: ['Brown'],
  },
  {
    category: 'chair',
    name: 'Kayoom',
    fullName: 'Kayoom home & office chair',
    productInfo:
      'The chair has a spectacular design and an amazing level of comfort. The model is great for contemporary or modern designs. Soft seat filled with polyurethane foam and comfortable armrests provide a comfortable stay. Metal legs are responsible for the stability and durability of the product.',
    img: 'https://i.ibb.co/rmxHVym/IMG-7130.jpg',
    price: 119,
    width: 570,
    height: 500,
    weight: 150,
    type: 'Work',
    feature: ['Armrest', 'Back'],
    color: ['Gray'],
  },
  {
    category: 'chair',
    name: 'Soule',
    fullName: 'Soule home & office chair',
    productInfo:
      'Enveloped in brushed polyester upholstery, this chair features a high backrest with steep, integrated arms and around the seat. Button tufting piped edges, and nail head trim lends a tailored touch, while foam fill offers comfort and support.',
    img: 'https://i.ibb.co/9pPMFG5/IMG-7132.jpg',
    price: 459,
    width: 560,
    height: 610,
    weight: 125,
    type: 'Work',
    feature: ['Armrest', 'Swivel', 'Tilting', 'Back'],
    color: ['Beige'],
  },
  {
    category: 'chair',
    name: 'Camilla',
    fullName: 'Camilla swivel desk chair',
    productInfo:
      'Featuring plush velvet upholstery, polished brass legs, and a plump silhouette worth sinking into, this chair features a 360 degree swivel.',
    img: 'https://i.ibb.co/QbfddX9/IMG-7133.jpg',
    price: 319,
    width: 600,
    height: 470,
    weight: 120,
    type: 'Work',
    feature: ['Armrest', 'Swivel', 'Back'],
    color: ['Blue'],
  },
  {
    category: 'chair',
    name: 'Highkas',
    fullName: 'High adjustable computer swivel office chair',
    productInfo:
      'This is a classic Nordic style chair, it is widely used in home office computer chairs, cafes, tea houses, and the natural thick sponge is very comfortable. Can lift and turn, five star aluminum alloy legs, fixed armrests, support ergonomic design, solid, durable and beautiful.',
    img: 'https://i.ibb.co/5xMHD9G/IMG-7134.jpg',
    price: 582,
    width: 450,
    height: 460,
    weight: 120,
    type: 'Work',
    feature: ['Armrest', 'Swivel', 'Tilting', 'Back'],
    color: ['White'],
  },
  {
    category: 'chair',
    name: 'Lathrup',
    fullName: 'Lathrup office chair',
    productInfo:
      'The French-inspired style is accented by a natural rustic finish and a neutral linen upholstered seat. Antique brass castors allow for easy movement, while the swivel capability makes it simple to pivot in and out of the seat.',
    img: 'https://i.ibb.co/PZmyWdj/IMG-7135.jpg',
    price: 349,
    width: 510,
    height: 460,
    weight: 125,
    type: 'Work',
    feature: ['Swivel', 'Back'],
    color: ['White'],
  },
  {
    category: 'chair',
    name: 'Donato',
    fullName: 'Curved walnut dining chair',
    productInfo:
      'The Curved Walnut Dining Chair, represents both luxury and comfort. The plush curves offer a reimagined modern take on 1970’s design. Rich warm walnut is paired with textural off-white boucle creating a show stopping elegant dining chair.',
    img: 'https://i.ibb.co/jwPdhZf/IMG-7136.jpg',
    price: 475,
    width: 520,
    height: 450,
    weight: 140,
    type: 'Dining',
    feature: ['Armrest', 'Back'],
    color: ['White'],
  },
  {
    category: 'chair',
    name: 'Parsons',
    fullName: 'Tufted parsons chair',
    productInfo:
      'The chairs are wrapped in polyester-blend upholstery in a neutral hue, and they stand on solid wood tapered legs with a black finish. Each armless chair features a classic wingback silhouette and a foam- and cotton-filled seat cushion for extra support.',
    img: 'https://i.ibb.co/ZHb1LMY/IMG-7137.jpg',
    price: 199,
    width: 480,
    height: 430,
    weight: 90,
    type: 'Dining',
    feature: ['Back'],
    color: ['Gray'],
  },
  {
    category: 'chair',
    name: 'Monkey',
    fullName: 'Monkey velvet chair',
    productInfo:
      'With its art deco-inspired design, luxe velvet upholstery and legs, and matte brass feet: this velvet chair is a flamboyant addition to any table.',
    img: 'https://i.ibb.co/f9Gr0H8/IMG-7138.jpg',
    price: 379,
    width: 510,
    height: 460,
    weight: 120,
    type: 'Dining',
    feature: ['Back'],
    color: ['Brown'],
  },
  {
    category: 'chair',
    name: 'Bruneta',
    fullName: 'Bruneta dining side chair',
    productInfo:
      'Whether pulled up to your dining room ensemble or accenting your bedroom or living room look, this side chair brings contemporary style with a touch of rustic appeal to any space.',
    img: 'https://i.ibb.co/9nqXwFT/IMG-7141.jpg',
    price: 409,
    width: 460,
    height: 480,
    weight: 115,
    type: 'Dining',
    feature: ['Back'],
    color: ['Green'],
  },
  {
    category: 'chair',
    name: 'Melting',
    fullName: 'Melting light dining chair',
    productInfo:
      'The Melting Light chair is good on its own and looks great as part of a dining group. The back on the metal frame is reinforced with a wooden lining, bent using a special technology. The legs are trimmed with gilded heels.',
    img: 'https://i.ibb.co/bvGfsQD/IMG-7142.jpg',
    price: 2745,
    width: 510,
    height: 490,
    weight: 140,
    type: 'Dining',
    feature: ['Back'],
    color: ['Beige'],
  },
  {
    category: 'chair',
    name: 'Danvers',
    fullName: 'Danvers dining chair',
    productInfo:
      'The utmost in style and sophistication, Danvers dining chair will help pull the look of your space together while offering comfortable seating to relax and dine in.',
    img: 'https://i.ibb.co/HDmcrZ3/IMG-7143.jpg',
    price: 135,
    width: 430,
    height: 460,
    weight: 125,
    type: 'Dining',
    feature: ['Back'],
    color: ['Gray'],
  },
  {
    category: 'chair',
    name: 'Tabla',
    fullName: 'Tabla dining chair',
    productInfo:
      'Designed to add a touch of the tropics to your dining area, the Tabla flaunts a juxtaposition of clean lines and soft fabric tones that give it an elegant vibe.',
    img: 'https://i.ibb.co/T8j5n4W/IMG-7144.jpg',
    price: 782,
    width: 530,
    height: 430,
    weight: 110,
    type: 'Dining',
    feature: ['Armrest', 'Back'],
    color: ['Brown'],
  },
  {
    category: 'chair',
    name: 'Jooseppi',
    fullName: 'Jooseppi dining chair',
    productInfo:
      'The authentic appeal of natural materials such as rattan creates furniture that is airy and light – the perfect look for a relaxed decor where the emphasis is on the Summery or exotic.',
    img: 'https://i.ibb.co/WcJzNBq/IMG-7145.jpg',
    price: 352,
    width: 530,
    height: 530,
    weight: 125,
    type: 'Dining',
    feature: ['Armrest', 'Back'],
    color: ['Brown'],
  },
  {
    category: 'chair',
    name: 'Losurdo',
    fullName: 'Losurdo upholstered armchair',
    productInfo:
      'This attractive wood-framed chair has it all: Style, Comfort, and Durability. Created with plush foam cushioning that encourages you to settle in and relax. It features a unique open-framed arm design, complete with rounded wooden accent bolt covers for an authentic retro finish. The comfortably padded seat and back cushions are finished in microfiber for an elegant finishing touch.',
    img: 'https://i.ibb.co/Qpg1yRH/IMG-7147.jpg',
    price: 174,
    width: 710,
    height: 460,
    weight: 115,
    type: 'Armchair',
    feature: ['Armrest', 'Back'],
    color: ['Beige'],
  },
  {
    category: 'chair',
    name: 'Jonah',
    fullName: 'Jonah armchair',
    productInfo:
      'A curved chair with a slender profile, Jonah wraps you in comfort. Its deep seat offers room to sink in and relax, while its rounded back and sloped arms offer the perfect reading or conversation spot next to a sofa or in a corner of your bedroom.',
    img: 'https://i.ibb.co/MCkYf4j/IMG-7148.jpg',
    price: 286,
    width: 560,
    height: 460,
    weight: 120,
    type: 'Armchair',
    feature: ['Armrest', 'Back'],
    color: ['Gray'],
  },
  {
    category: 'chair',
    name: 'Ronaldo',
    fullName: 'Ronaldo upholstered lounge chair',
    productInfo:
      "This armchair provides another seat for living room groups and gives your reading nook a bit of mid-century modern flair. It's crafted from solid rubberwood, and it rests on angled legs that come in a natural brown hue for a bit of boho charm. The seat and back show off plush polyester upholstery in a neutral tone that blends in nicely with various styles and color schemes. Rounded square arms bring an open feel to the overall design, while the low profile completes the look.",
    img: 'https://i.ibb.co/WnSVV5M/IMG-7149.jpg',
    price: 399,
    width: 610,
    height: 405,
    weight: 135,
    type: 'Armchair',
    feature: ['Armrest', 'Back'],
    color: ['Beige'],
  },
  {
    category: 'chair',
    name: 'Mole',
    fullName: 'Mole armchair',
    productInfo:
      'The "Mole" armchair (meaning "soft" in Portuguese) is comprised of a solid rounded wood frame, adjustable leather support straps and floppy, over-sized luxurious leather cushions. Robust and extremely comfortable, the "Mole" sparked an international design trend that favored comfort, and a new attention to scale, over the rigid and antiseptic concurrent design trends.',
    img: 'https://i.ibb.co/HTFXGQN/IMG-7150.jpg',
    price: 419,
    width: 750,
    height: 420,
    weight: 105,
    type: 'Armchair',
    feature: ['Armrest', 'Back'],
    color: ['White'],
  },
  {
    category: 'chair',
    name: 'Merax',
    fullName: 'Merax armchair',
    productInfo:
      'This armchair is made of high-density and high-resilient foam, which can provide maximum comfort for you. Teddy short plush particle velvet is soft to the touch, resistant to stains and discoloration, and gives you comfortable sitting.',
    img: 'https://i.ibb.co/2W2PLvv/IMG-7151.jpg',
    price: 279,
    width: 535,
    height: 430,
    weight: 125,
    type: 'Armchair',
    feature: ['Armrest', 'Back'],
    color: ['White'],
  },
  {
    category: 'chair',
    name: 'Petra',
    fullName: 'Petra lounge chair',
    productInfo:
      'Tradition’s Petra lounge chairs charm with their compact size, flowing silhouette and soft sheepskin upholstery. The petite, friendly chair is a lovable example of the Danish funkis style of the 1930s.',
    img: 'https://i.ibb.co/x2X6MZ5/IMG-7152.jpg',
    price: 2856,
    width: 520,
    height: 460,
    weight: 120,
    type: 'Armchair',
    feature: ['Back'],
    color: ['Beige'],
  },
  {
    category: 'chair',
    name: 'Boucle',
    fullName: 'Upholstered Boucle armchair',
    productInfo:
      'Upholstered armchair in bouclé fabric with contrast wooden sides and legs. Includes adjustable buffers at the bottom of each leg, designed to maintain stability and prevent the legs from scratching the ground.',
    img: 'https://i.ibb.co/LxxtCCn/IMG-7153.jpg',
    price: 281,
    width: 680,
    height: 450,
    weight: 120,
    type: 'Armchair',
    feature: ['Back'],
    color: ['White'],
  },
  {
    category: 'chair',
    name: 'Poyet',
    fullName: 'Poyet armchair',
    productInfo:
      'Armchair Poet is made in the Scandinavian style. Comfortable and original, it combines hornbeam wood and soft fabric upholstery. Functionality and style, high quality and simple, pleasing to the eye proportions - all this is combined in this chair model.',
    img: 'https://i.ibb.co/9HRZSD8/IMG-7154.jpg',
    price: 1083,
    width: 720,
    height: 400,
    weight: 130,
    type: 'Armchair',
    feature: ['Back'],
    color: ['Gray'],
  },
  {
    category: 'chair',
    name: 'Finley',
    fullName: 'Finley armchair',
    productInfo: 'A classic English reading chair with elegant curves.',
    img: 'https://i.ibb.co/JyZ9g1x/IMG-7155.jpg',
    price: 859,
    width: 700,
    height: 400,
    weight: 135,
    type: 'Armchair',
    feature: ['Armrest', 'Back'],
    color: ['Green'],
  },
  {
    category: 'chair',
    name: 'Sundae',
    fullName: 'Sundae armchair',
    productInfo:
      'The voluminous Sundae seating challenges the typical construction of lounges, which sees the utilization of an excess of material to retain structure.',
    img: 'https://i.ibb.co/yF1K2bK/IMG-7156.jpg',
    price: 4470,
    width: 850,
    height: 400,
    weight: 140,
    type: 'Armchair',
    feature: ['Armrest', 'Back'],
    color: ['White'],
  },
  {
    category: 'chair',
    name: 'Cassette',
    fullName: 'Cassette armchair',
    productInfo:
      'Underpinned by a minimalist and sophistication aesthetic of clean lines.',
    img: 'https://i.ibb.co/fq7hFcb/IMG-7158.jpg',
    price: 2188,
    width: 900,
    height: 420,
    weight: 140,
    type: 'Armchair',
    feature: ['Armrest', 'Back'],
    color: ['White'],
  },
  {
    category: 'chair',
    name: 'Entertain',
    fullName: 'Entertain velvet armchair',
    productInfo:
      'Entertain features plush dense foam padding with soft, stain-resistant performance velvet upholstery for a luxurious seating experience that delivers premium comfort. Introduce this cozy, extra wide retro-modern centerpiece to your living room or lounge area.',
    img: 'https://i.ibb.co/C8cvv9j/IMG-7159.jpg',
    price: 760,
    width: 830,
    height: 380,
    weight: 140,
    type: 'Armchair',
    feature: ['Armrest', 'Back'],
    color: ['Pink'],
  },
  {
    category: 'chair',
    name: 'Zoe',
    fullName: 'Zoe armchair',
    productInfo:
      'To bring in a touch of style, a hint of comfort and a bit of flair, try adding our Zoe accent chair. In any space, this piece is the perfect conversation starter thanks to its trendy mid-century-inspired design.',
    img: 'https://i.ibb.co/j4fhz2s/IMG-7160.jpg',
    price: 695,
    width: 660,
    height: 530,
    weight: 115,
    type: 'Armchair',
    feature: ['Armrest', 'Back'],
    color: ['Blue'],
  },
  {
    category: 'chair',
    name: 'Wells',
    fullName: 'Wells upholstered tufted swivel armchair',
    productInfo:
      'Handsomely styled with a modified wingback, Wells makes even a small room feel like a cozy study. We love its shapely silhouette – comfy and enveloping. The swivel design is a real head turner, and the traditional button tufting is as classic as it gets.',
    img: 'https://i.ibb.co/870dG7T/IMG-7161.jpg',
    price: 1649,
    width: 510,
    height: 510,
    weight: 110,
    type: 'Armchair',
    feature: ['Armrest', 'Back', 'Swivel'],
    color: ['Gray'],
  },
  {
    category: 'chair',
    name: 'Mel',
    fullName: 'Velvet easy chair with armrests',
    productInfo:
      'Mel is a wooden armchair. Mel – honey – embodies the soothing feeling of nature’s purest and sweetest gift. A relaxing and cosy armchair made just for you, with undeniable therapeutic benefits.',
    img: 'https://i.ibb.co/smsJzT3/IMG-7162.jpg',
    price: 899,
    width: 780,
    height: 400,
    weight: 120,
    type: 'Armchair',
    feature: ['Armrest', 'Back'],
    color: ['Gray'],
  },
  {
    category: 'chair',
    name: 'Spot',
    fullName: 'Spot stool',
    productInfo:
      "A deconstructed cylindrical shape refined to its bare essentials, the Spot Stool designed by Michael Anastassiades has a purity of form and an honesty of materials that have become the designer's signature. A circular seat and base are held together by two parallel legs in the kindred pairing of wood and metal.",
    img: 'https://i.ibb.co/VHZWZHR/IMG-7247.jpg',
    price: 1045,
    width: 330,
    height: 610,
    weight: 115,
    type: 'Dining',
    feature: [''],
    color: ['Brown'],
  },
  {
    category: 'chair',
    name: 'Clasby',
    fullName: 'Clasby bar stool',
    productInfo:
      'An energetic design offers the perfect style to dress up in a modern space. A unique texture and detail make this stool a standout, with a simple wooden frame topped with a woven leather seat. Strips of genuine leather crisscross to form a basket woven construction topping four squared legs with built-in footrests.',
    img: 'https://i.ibb.co/ZSjFP51/IMG-7249.jpg',
    price: 296,
    width: 460,
    height: 710,
    weight: 115,
    type: 'Dining',
    feature: [''],
    color: ['Brown'],
  },
  {
    category: 'chair',
    name: 'Riviera',
    fullName: 'Riviera backless bar & counter stools',
    productInfo:
      'The classic Parisian bistro chair, reinvented. True to its roots, each rattan frame is crafted in a time-honored technique perfected by the French, bent and shaped by hand until the iconic shape is achieved. The seats are woven from the finest quality rattan and lightweight resin, making them fabulously family-friendly and great for dining spaces.',
    img: 'https://i.ibb.co/SyN35jb/IMG-7250.jpg',
    price: 298,
    width: 380,
    height: 660,
    weight: 115,
    type: 'Dining',
    feature: [''],
    color: ['Brown', 'White'],
  },
  {
    category: 'chair',
    name: 'Hylie',
    fullName: 'Hylie counter stool',
    productInfo:
      'Enjoy a refreshing update to your home bar with this Set of 2 Bar Stools. Constructed with a cushioned seat and wooden frame legs with stretchers, this backless chair is sturdy and never goes out of style. Perfect for contemporary kitchen counters or pub tables.',
    img: 'https://i.ibb.co/88NcqCk/IMG-7251.jpg',
    price: 160,
    width: 430,
    height: 610,
    weight: 115,
    type: 'Dining',
    feature: [''],
    color: ['Beige', 'White'],
  },
];
