import { Decorations } from '../interfaces/decorations-interface';

export const decorations: Decorations[] = [
  {
    category: 'decoration',
    name: 'Donut',
    fullName: 'Modern minimalistic circle vase',
    productInfo:
      'Vase mouth flat cut round, perfect with natural flowers, artificial flowers or pampas plants; Vase body with donut hollow design, the ceramic vase can be placed independently in the living room or bedroom as a decorative piece; Vase has a smooth base with frosted gold matte finish.',
    img: 'https://i.ibb.co/PZRhFYP/IMG-7255.jpg',
    price: 22,
    type: 'Vase',
    material: ['Ceramic'],
    color: ['White'],
  },
  {
    category: 'decoration',
    name: 'Emotion',
    fullName: 'Minimalist decorative vase',
    productInfo:
      "Abstract Ceramic Vase - Special vivid face lines design style. Made with high quality ceramic. The vase for living room decoration match your exotic houseplants, wintry florals, shelf decor, floor table decorations, and fall decor for home. fireplace decor, and entry table decor. A pretty handy ceramic decor despite it's size and simple design.",
    img: 'https://i.ibb.co/wgh7R5G/IMG-7256.jpg',
    price: 20,
    type: 'Vase',
    material: ['Ceramic'],
    color: ['White'],
  },
  {
    category: 'decoration',
    name: 'Urna',
    fullName: 'Urna vase',
    productInfo:
      'The Urna vase is a shallower version with a wider opening, great for larger flower arrangements. Beautiful by itself or in combination with the Ming vase.',
    img: 'https://i.ibb.co/gJ71M48/IMG-7257.jpg',
    price: 15,
    type: 'Vase',
    material: ['Glass'],
    color: ['White'],
  },
  {
    category: 'decoration',
    name: 'Mcgee',
    fullName: 'Mcgee glass vase',
    productInfo:
      'A classic handblown glass bottle in an attractive, transparent black shade. The body is broad at the center, with a slightly tapered bottom and thin neck. The lip is smooth and has a lightly beveled edge. It is the perfect statement piece for showcasing your favorite blooms anywhere in your home. Please note that slight variations in finish are expected due to the crafting materials of glass.',
    img: 'https://i.ibb.co/gj68Xqd/IMG-7258.jpg',
    price: 183,
    type: 'Vase',
    material: ['Glass'],
    color: ['Black'],
  },
  {
    category: 'decoration',
    name: 'Bella',
    fullName: 'Human face art ceramic vase',
    productInfo:
      'The ceramic vase adopts the human face body art design, which is simple and charming. The special design style of the vase can be matched with dried flowers, artificial flowers and green plants. This will be a beautiful landscape in your home.',
    img: 'https://i.ibb.co/p03V4y5/IMG-7259.jpg',
    price: 45,
    type: 'Vase',
    material: ['Ceramic'],
    color: ['White'],
  },
  {
    category: 'decoration',
    name: 'Kruk',
    fullName: 'Nordic vase decoration home',
    productInfo:
      'The product style uses European and American simple winds, simple atmosphere, can match a variety of bouquets and simulation bouquets, bring a visual feast. Vase can be used for wedding, party, indoor living room bedroom restaurant, courtyard decoration, holiday decoration, etc.',
    img: 'https://i.ibb.co/YjHT5X0/IMG-7260.jpg',
    price: 16,
    type: 'Vase',
    material: ['Plastic'],
    color: ['White'],
  },
  {
    category: 'decoration',
    name: 'Chimney',
    fullName: 'Chimney charred vase in "Barro Preto"',
    productInfo:
      'The Chimney vase is part of the collection "Charred Vases", five unique forms made in the dying Portuguese art of Barro Preto. Buried and fired in an underground pit called a Soenga, this process of smothering the ceramic removes oxygen and results in a non-homogenous texture of black, grey and earth tones. A vanishing tradition – there are few artisans left who have the knowledge to produce objects in Barro Preto. Together with João Lourenço, Gabriel Tan wishes to rekindle this heritage. The barro preto is a non-homogenous texture of black, grey and earth tones.',
    img: 'https://i.ibb.co/4JgkDJG/IMG-7261.jpg',
    price: 371,
    type: 'Vase',
    material: ['Ceramic'],
    color: ['Black'],
  },
  {
    category: 'decoration',
    name: 'Pleat',
    fullName: 'Pleat glass vase',
    productInfo:
      'Create a stunning floral display with this Pleat vase. Crafted from mouth-blown glass, this vase has been inspired by the draping and gathering of pleated fabric. A welcome addition to any home.',
    img: 'https://i.ibb.co/0DcQSq6/IMG-7262.jpg',
    price: 99,
    type: 'Vase',
    material: ['Glass'],
    color: ['Black'],
  },
  {
    category: 'decoration',
    name: 'Killian',
    fullName: 'Metal water jar',
    productInfo:
      'An antique Indian metal water jar from the 19th century, with large belly, slender neck and large lip. Born in India during the 19th century, this metal water jar charms our eyes with its generous Silhouette and nicely weathered patina. Presenting a large belly topped with a thin neck and protruding lip, the jar will make for a great decorative addition in any home, perhaps placed on a rustic coffee table on a patio, or buffet or dining table.',
    img: 'https://i.ibb.co/44f8nLG/IMG-7263.jpg',
    price: 375,
    type: 'Vase',
    material: ['Metal'],
    color: ['Black'],
  },
  {
    category: 'decoration',
    name: 'Stilren',
    fullName: 'Stilren vase',
    productInfo:
      'A nice vase with flowers can brighten up just about any day. This vase makes it easy to decorate with natural beauty in your home and is perfect for bouquets.',
    img: 'https://i.ibb.co/BtsBgpL/IMG-7264.jpg',
    price: 15,
    type: 'Vase',
    material: ['Ceramic'],
    color: ['White'],
  },
  {
    category: 'decoration',
    name: 'Tear',
    fullName: 'Vase for home decor',
    productInfo:
      'This decorative ceramic vase will fit in with an abundance of styles; classic, traditional, farmhouse or boho modern decor - goes with any style. Beautifully glazed and textured.',
    img: 'https://i.ibb.co/5LTCfBg/IMG-7265.jpg',
    price: 38,
    type: 'Vase',
    material: ['Ceramic'],
    color: ['Blue'],
  },
  {
    category: 'decoration',
    name: 'Tear',
    fullName: 'Vase for home decor',
    productInfo:
      'This decorative ceramic vase will fit in with an abundance of styles; classic, traditional, farmhouse or boho modern decor - goes with any style. Beautifully glazed and textured.',
    img: 'https://i.ibb.co/5LTCfBg/IMG-7265.jpg',
    price: 38,
    type: 'Vase',
    material: ['Ceramic'],
    color: ['Blue'],
  },
  {
    category: 'decoration',
    name: 'Nami',
    fullName: 'Nami brass pot, tapered',
    productInfo:
      'Make a stylish addition to your interior with the Nami Tapered pot. Hammered into shape from antique brass, this tapered brass pot features a hand etched design on the exterior. Completely watertight, the Nami pot can be used as a vase for flowers as well as a standalone decorative piece.',
    img: 'https://i.ibb.co/zmpn9Wv/IMG-7267.jpg',
    price: 415,
    type: 'Vase',
    material: ['Metal'],
    color: ['Gold'],
  },
  {
    category: 'decoration',
    name: 'Eres',
    fullName: 'Eres green glass bottle',
    productInfo:
      'Our vintage inspired Eres green glass bottle is the perfect decorative accent for any space. This classic reproduction green glass jug can be used as a vase for floral arrangements or simply as a decorative accent.',
    img: 'https://i.ibb.co/PFMghr6/IMG-7268.jpg',
    price: 98,
    type: 'Vase',
    material: ['Glass'],
    color: ['Green'],
  },
  {
    category: 'decoration',
    name: 'Human',
    fullName: 'Abstract head flower vase',
    productInfo:
      'Artistic planter can be filled with various plants decorations such as flowers, branches, pebbles and other vase fillers, wich can fresh and clean feeling to the patio, garden, bookstore or table indoors. The flower vase can be used as a succulent planter, planter, flower vase. The creative and charming appearance of the character flower pots perfectly decorates your living space, small it always a decoration in the study, office, desktop, bedroom, kitchen, balcony, etc.',
    img: 'https://i.ibb.co/dcSbCxj/IMG-7269.jpg',
    price: 220,
    type: 'Vase',
    material: ['Ceramic'],
    color: ['White'],
  },
  {
    category: 'decoration',
    name: 'Peony',
    fullName: 'Flower bouquets of glorious peony',
    productInfo:
      'Artificial peony flowers, bouquet height about 30cm, each bouquet has 5 forks, with 5 large flowers and 4 flower core. Each flower is handmade.Realistic artificial flower, pure and elegant, to the touch, made of silk. The package includes 4 flower bouquets.',
    img: 'https://i.ibb.co/VvDfjzs/IMG-7276.jpg',
    price: 21,
    type: 'Artificial flower',
    material: ['Plastic', 'Silk'],
    color: ['Pink'],
  },
  {
    category: 'decoration',
    name: 'Rose',
    fullName: 'Artificial rose bouquet',
    productInfo:
      'This 5 heads rose bouquet adopts soft and smooth silk cloth, can provide a good touch feeling. The fake rose bouquet features a appearance, is a good alternative for a real flower. The flower stem is made of plastic, can stay strong and sturdy, not easy to break. The fake flower bouquet is a good choice for a wedding, party, ceremony decoration. The color is healthy and safe to use, and is not easy to wither, is convenient to maintain. The package includes 4 flower bouquets.',
    img: 'https://i.ibb.co/kSsx7qP/IMG-7277.jpg',
    price: 26,
    type: 'Artificial flower',
    material: ['Plastic', 'Silk'],
    color: ['Purple'],
  },
  {
    category: 'decoration',
    name: 'Peony',
    fullName: 'Peony with stems',
    productInfo:
      'These artificial peonies are rich in flowers, buds and some green leaves, and can be used to put into a vase or potted plant for landscaping. It also can be wrapped as a wedding bouquet. Realistic petal effect, clear texture, uniform dyeing. A bunch of artificial peonies has about 5 flowers and 4 flower buds. One set has 4PCS.',
    img: 'https://i.ibb.co/RDDYq3X/IMG-7278.jpg',
    price: 15,
    type: 'Artificial flower',
    material: ['Plastic'],
    color: ['White'],
  },
  {
    category: 'decoration',
    name: 'Sakura',
    fullName: 'Artificial cherry blossom branches',
    productInfo:
      'Tall Pink Silk Cherry Blossoms. Each stem features 5-branches and 75 realistic cherry blossom flowers. Each artificial cherry blossom features 5-branches that are wired from top to bottom. This will allow you to bend and shape the branches in any direction to create a three-dimensional look. Save money and time with our realistic cherry blossoms. The artificial flowers and leaves are made of high-quality silk. Each cherry blossom stem is made of wire for greater control over arrangement and display. Use silk cherry blossoms in their weddings, centerpieces, floral arrangements, home decor, farmhouse decor, dining table arrangements, office decorations. The set includes 4 branches.',
    img: 'https://i.ibb.co/vksMdLn/IMG-7279.jpg',
    price: 55,
    type: 'Artificial flower',
    material: ['Silk'],
    color: ['White'],
  },
  {
    category: 'decoration',
    name: 'Plum',
    fullName: 'Plum artificial flowers',
    productInfo:
      'Bring the outdoors in, delivering a bright, nature-filled aura to your spring and summertime surroundings with this sweet white artificial blossom stem! This sweet stem is great to use in weddings and special events, though you can just as easily use this to bring romantic charm to your home. Adorn your kitchens, bathrooms, and table settings! Place in vases, bottles, canisters and tin buckets. This flower branch could be combined with picks, green plants, or other floral stems. Even lay it flat as a dainty centerpiece!',
    img: 'https://i.ibb.co/mSx8wB9/IMG-7280.jpg',
    price: 77,
    type: 'Artificial flower',
    material: ['Silk'],
    color: ['White'],
  },
  {
    category: 'decoration',
    name: 'Orchid',
    fullName: 'Faux orchid plant & concrete vessel',
    productInfo:
      'Cultivate a lush interior landscape with our exclusive pairing of handcrafted greenery and sculptural vessels. Our faux orchid plant, an exquisite botanical accent with exceptional realism, is custom designed and exactingly molded to fit our Carved Concrete Vessel. The effect is instantly vibrant and textural, with a natural-looking beauty that lasts season after season.',
    img: 'https://i.ibb.co/nw3KHyr/IMG-7283.jpg',
    price: 290,
    type: 'Artificial flower',
    material: ['Silk'],
    color: ['White'],
  },
  {
    category: 'decoration',
    name: 'Tulips',
    fullName: 'Royal blue artificial tulips (set of 20)',
    productInfo:
      'These tulips looks lifelike and has a real touch. No color fading and no flower drop off. Perfect room decor for Easter brunch centerpiece, Halloween, spring floral arrangement, tulip door wreath, wedding bouquets, house, office, party, garden, hotel, cafes, festival, celebration.',
    img: 'https://i.ibb.co/dJsjF3G/IMG-7284.jpg',
    price: 25,
    type: 'Artificial flower',
    material: ['Silk', 'Plastic'],
    color: ['Blue'],
  },
  {
    category: 'decoration',
    name: 'Cotton',
    fullName: 'Naturally dried cotton',
    productInfo:
      'Stems are made from cotton bolls and floral wire wrapped in brown rustic floral tape, making it simple to reshape each stem for optimal home decor staging. Can be used for home decoration or flower arrangement. Handmade, good quality, roots and stems can be bent, can be adjusted according to personal preferences.',
    img: 'https://i.ibb.co/qFpMVgR/IMG-7285.jpg',
    price: 8,
    type: 'Artificial flower',
    material: ['Other'],
    color: ['White'],
  },
  {
    category: 'decoration',
    name: 'Pampas',
    fullName: 'Pampas grass (set of 6)',
    productInfo:
      'Durability, real and natural than artificial flowers, can be used continuously for more than one year, not subject to seasonal restrictions, generally does not fade. Add an artistic atmosphere to the living environment and make the living environment more flavorful. Perfect for making bouquets, centerpieces, boutonnieres, cake flowers or any other flower decorations and arrangements that you want at your wedding, party, baby shower or home.',
    img: 'https://i.ibb.co/Zg85KyF/IMG-7286.jpg',
    price: 6,
    type: 'Artificial flower',
    material: ['Other'],
    color: ['Other'],
  },
  {
    category: 'decoration',
    name: 'Lavender',
    fullName: 'Natural dried flowers lavender',
    productInfo:
      'Bring the beautiful blues of lavender indoors with our fragrant bundles of dried flower stems artfully wrapped in brown craft paper. When placed in a basket or displayed on a shelf or table, they add natural beauty to an office, kitchen, or bath while subtly perfuming the air with their soothing, all-natural fragrance. Makes an enduring gift for someone special, too.',
    img: 'https://i.ibb.co/Lr9JwzB/IMG-7287.jpg',
    price: 14,
    type: 'Artificial flower',
    material: ['Other'],
    color: ['Blue'],
  },
  {
    category: 'decoration',
    name: 'Eucalyptus',
    fullName: 'Artificial eucalyptus (set of 5)',
    productInfo:
      'This artificial eucalyptus is perfect for adding greenery to your displays. The stem features large leaves. Add it to a flower arrangement, wreath or other decoration.',
    img: 'https://i.ibb.co/0V5djs0/IMG-7288.jpg',
    price: 22,
    type: 'Artificial flower',
    material: ['Silk'],
    color: ['Green'],
  },
  {
    category: 'decoration',
    name: 'Hydrangea',
    fullName: 'Artificial hydrangea bouquet with small ceramic vase',
    productInfo:
      'Flowers and leaves are made of high quality plastic for easy care. The flower pot is made of ceramic, simple but beautiful, it is crafted to be more realistic than other artificial plants on the market. No need for maintenance or care, they will neither wither nor fade. The bouquet may be squeezed during long-distance transportation. You can straighten the leaves by hand, squeeze the flower head appropriately, and leave it for a period of time, the flower will return to its original shape. We believe that through your arrangement, it will become more beautiful.',
    img: 'https://i.ibb.co/N24LGTD/IMG-7289.jpg',
    price: 14,
    type: 'Artificial flower',
    material: ['Silk', 'Plastic'],
    color: ['Green', 'Blue', 'White'],
  },
  {
    category: 'decoration',
    name: 'Chrysanthemum',
    fullName: 'Artificial potted flower',
    productInfo:
      'This sweet bouquet would look spectacular in your home or special event. They are a great alternative to fresh flowers and they never wilt!',
    img: 'https://i.ibb.co/Css1VLY/IMG-7290.jpg',
    price: 5,
    type: 'Artificial flower',
    material: ['Plastic'],
    color: ['Pink'],
  },
  {
    category: 'decoration',
    name: 'Plant',
    fullName: 'Artificial plants in a pot',
    productInfo:
      'This sweet bouquet would look spectacular in your home or special event. They are a great alternative to fresh flowers and they never wilt!',
    img: 'https://i.ibb.co/tqYX2Y6/IMG-7291.jpg',
    price: 3,
    type: 'Artificial flower',
    material: ['Plastic'],
    color: ['Green'],
  },
  {
    category: 'decoration',
    name: 'Lavender',
    fullName: 'Artificial lavender plant in a pot',
    productInfo:
      'This is detailed replicas of the fragrant lavender plant and inspire with their color intensity and the perfect imitation of flowers. High-quality cement pots enclose the decorative plants. You can place your new perpetual bloomers on window sills or chests of drawers in the living room, regardless of the amount of sunlight.',
    img: 'https://i.ibb.co/d2STmmc/IMG-7292.jpg',
    price: 30,
    type: 'Artificial flower',
    material: ['Plastic'],
    color: ['Purple'],
  },
  {
    category: 'decoration',
    name: 'Bougie',
    fullName: 'Soy wax candle',
    productInfo:
      'Soy wax candle is made from soybeans. Non-toxic, biodegradable, environmentally friendly. Wick is metal-free and made from unbleached cotton. Burns cleanly and ensures perfect aroma distribution.',
    img: 'https://i.ibb.co/9wytF0s/IMG-7293.jpg',
    price: 19,
    type: 'Candle',
    material: ['Wax'],
    color: ['Black'],
  },
  {
    category: 'decoration',
    name: 'Easter',
    fullName: 'Concrete Easter candle (set of 2)',
    productInfo:
      'These Easter egg-shaped candles with a concrete base will add zest to your celebration.',
    img: 'https://i.ibb.co/NFpwzf8/IMG-7294.jpg',
    price: 39,
    type: 'Candle',
    material: ['Wax'],
    color: ['White'],
  },
  {
    category: 'decoration',
    name: 'Lavender',
    fullName: 'Scented candle in a glass',
    productInfo:
      'Lavender is well known for its calming effects. Be it as a sleeping aid for small children or as a relaxing bath for a short wellness moment, lavender is and remains a popular classic for all situations in life.',
    img: 'https://i.ibb.co/GTh2HVN/IMG-7295.jpg',
    price: 13,
    type: 'Candle',
    material: ['Wax'],
    color: ['White'],
  },
  {
    category: 'decoration',
    name: 'Botanic',
    fullName: 'Botanical candle (set of 3)',
    productInfo:
      'Pretty pillar candle decorated with real dried pressed green leaves. Made with 100% all natural eco wax.',
    img: 'https://i.ibb.co/827K0W8/IMG-7296.jpg',
    price: 57,
    type: 'Candle',
    material: ['Wax'],
    color: ['White'],
  },
  {
    category: 'decoration',
    name: 'Forest',
    fullName: 'Scented candle in a wooden holder (set of 3)',
    productInfo:
      'The candlestick is made of natural material - elm wood. Each candle has its own unique pattern, relief and shade of bark. There are no two identical candles made of wood. Each is a unique natural specimen. Candles are created from ready-made wood raw materials, which are not suitable for the manufacture of standard wood products, not a single tree was harmed by our hands. The wooden base is treated with fire and biological protection, which protects the wood from mold, insects, and also counteracts fire.',
    img: 'https://i.ibb.co/4tVmrPc/IMG-7297.jpg',
    price: 76,
    type: 'Candle',
    material: ['Wax'],
    color: ['White'],
  },
  {
    category: 'decoration',
    name: 'Bubble',
    fullName: 'Bubble cube candle (set of 3)',
    productInfo:
      'With this candle you give your room a casual and elegant touch. Unlike the classic design of decorative candles, this candle is perfect for decorating any corner of the house, be it in a corner of the living room, in the hallway or on the bedroom table. With their very original design, in which their square shape is formed by a series of small balls in pastel tones, they are very trendy.',
    img: 'https://i.ibb.co/4F5pPSJ/IMG-7298.jpg',
    price: 45,
    type: 'Candle',
    material: ['Wax'],
    color: ['White', 'Gray', 'Pink'],
  },
  {
    category: 'decoration',
    name: 'Cube',
    fullName: 'Cube candle (set of 3)',
    productInfo:
      'Beautiful and complete dyed rustic design candles. The cutting-edge square design is a must have for decorating besonders stylish candle.',
    img: 'https://i.ibb.co/Dfy8Ckk/IMG-7299.jpg',
    price: 28,
    type: 'Candle',
    material: ['Wax'],
    color: ['Blue', 'Pink'],
  },
  {
    category: 'decoration',
    name: 'Moon',
    fullName: 'Moon candle (set of 2)',
    productInfo:
      'Welcome to the darkside! This glorious miniature moon candle measures 5.5cm high and 6cm across. Black wax and cotton wick, this celestial trinket is fragranced with Jasmine and vanilla.',
    img: 'https://i.ibb.co/wB1KnT3/IMG-7300.jpg',
    price: 22,
    type: 'Candle',
    material: ['Wax'],
    color: ['Black'],
  },
  {
    category: 'decoration',
    name: 'Column',
    fullName: 'Ribbed pillar candle (set of 3)',
    productInfo:
      'Our decorative pillar candles are the ultimate addition to your home decor. Our candles compliment a variety of styles including contemporary, chic minimal and more classic home decor styles.',
    img: 'https://i.ibb.co/PwdKW8x/IMG-7302.jpg',
    price: 27,
    type: 'Candle',
    material: ['Wax'],
    color: ['White'],
  },
  {
    category: 'decoration',
    name: 'Cozy',
    fullName: 'Scented candle with saying',
    productInfo:
      'Our candles smell wonderfully relaxing and ensure a cozy home. They decorate your room in style without any frills. Especially beneficial in stressful phases.',
    img: 'https://i.ibb.co/Lvd8x85/IMG-7303.jpg',
    price: 12,
    type: 'Candle',
    material: ['Wax'],
    color: ['White'],
  },
  {
    category: 'decoration',
    name: 'Orchids',
    fullName: 'Faux floral orchids with contemporary vase',
    productInfo:
      'Faux floral orchid arrangement. Made of plastic with stone and ceramic scoop vase.',
    img: 'https://i.ibb.co/HtkVd1G/IMG-7305.jpg',
    price: 330,
    type: 'Artificial flower',
    material: ['Plastic'],
    color: ['White'],
  },
];
