import { Lamps } from '../interfaces/lamps-interface';

export const lamps: Lamps[] = [
  {
    category: 'lamp',
    name: 'TaoTronic',
    fullName: 'Lamp aluminum alloy dimmable',
    productInfo:
      'Super premium aluminum alloy construction acts as passive heat sink, protect and prolong LED lifespan. 18 adjustable light choices including 6 brightness levels and 3 lighting modes to choose from, non-ghosting and non-flickering lighting ideal for work, study, reading and relaxing. USB port conveniently charge your devices, compatible with most smartphones and USB e-readers on the market. Memory function means you only need to set the brightness/color mode once, and IT will automatically return to the setting when turned on next time.',
    img: 'https://i.ibb.co/QHPnXs2/IMG-7163.jpg',
    price: 49,
    length: 360,
    switchType: ['Touch'],
    type: 'Desk',
    feature: ['Brightness control', 'USB port'],
    color: ['Metallic'],
  },
  {
    category: 'lamp',
    name: 'Edison',
    fullName: 'Industrial table lamp',
    productInfo:
      'The industrial desk Lamp is designed for a modern and elegant look. This charming design showcases a tubular metal body and lamp base with an exposed bulb for an added industrialized touch. The modern desk lamp can offer a smooth, comforting, and relaxed feeling to a house the second it is turned on. It is the perfect decor for a beautiful modern house.',
    img: 'https://i.ibb.co/hLvJVMs/IMG-7166.jpg',
    price: 29,
    length: 405,
    switchType: ['Button'],
    type: 'Desk',
    feature: [''],
    color: ['Gold'],
  },
  {
    category: 'lamp',
    name: 'Hampton',
    fullName: 'Black indoor LED desk lamp',
    productInfo:
      'This 3-Watt Black Indoor LED Desk Lamp features LED technology that is both energy efficient and stylish. The adjustable gooseneck can easily point the light in any direction that you need.',
    img: 'https://i.ibb.co/j6mGDZN/IMG-7167.jpg',
    price: 34,
    length: 380,
    switchType: ['Button'],
    type: 'Desk',
    feature: [''],
    color: ['Black'],
  },
  {
    category: 'lamp',
    name: 'Emmett',
    fullName: 'Emmett table lamp',
    productInfo:
      "The Emmett Table Lamp is an essential addition to sleek, modern decor. It's both functional and stylish. A small footprint allows this piece to fit neatly on the night stand or desk without taking up too much space. An adjustable shade allows for light to be directed where it is needed.",
    img: 'https://i.ibb.co/1Kh2Q6s/IMG-7168.jpg',
    price: 130,
    length: 585,
    switchType: ['Button'],
    type: 'Desk',
    feature: [''],
    color: ['White', 'Gold'],
  },
  {
    category: 'lamp',
    name: 'Ascoli',
    fullName: 'Ascoli desk lamp',
    productInfo:
      'Get down to business with the minimalist style Ascoli Desk Lamp from Astro Lighting. Sharp angles and graceful geometric shapes lend a sleek modern juxtaposition and a clean simplified aesthetic to this bold desk lamp, elevating workstations and home offices magnificently.',
    img: 'https://i.ibb.co/2h0yTRM/IMG-7170.jpg',
    price: 290,
    length: 421,
    switchType: ['Button'],
    type: 'Desk',
    feature: [''],
    color: ['Black'],
  },
  {
    category: 'lamp',
    name: 'Navlinge',
    fullName: 'LED work lamp',
    productInfo:
      'Gives directional light that is good for focused lighting. You can easily direct the light where you want it because the lamp arm and head are adjustable. The LED light source consumes up to 85% less energy and lasts 20 times longer than incandescent bulbs.',
    img: 'https://i.ibb.co/6yq6yym/IMG-7171.jpg',
    price: 19,
    length: 660,
    switchType: ['Button'],
    type: 'Desk',
    feature: [''],
    color: ['White'],
  },
  {
    category: 'lamp',
    name: 'Hongy',
    fullName: 'Nordic study lamp',
    productInfo:
      'With frosted shade and a long lamp head, it cast a broader span of soft light, efficiently reduce the contrast between your monitor and the surrounding area, creating a more comfortable environment for your eyes. It won’t hog space on your desk, fits nicely in any desk, work bench, sewing table, bedside nightstands, nail station etc.',
    img: 'https://i.ibb.co/71nRZ9v/IMG-7172.jpg',
    price: 39,
    length: 450,
    switchType: ['Button'],
    type: 'Desk',
    feature: [''],
    color: ['White', 'Brown'],
  },
  {
    category: 'lamp',
    name: 'Forsa',
    fullName: 'Work lamp with LED bulb',
    productInfo:
      'Classic style work lamp in steel that will brighten up your day. The arm and shade are adjustable which makes it a great lamp for reading by the desk, bed or sofa.',
    img: 'https://i.ibb.co/GFYQy9m/IMG-7173.jpg',
    price: 34,
    length: 355,
    switchType: ['Button'],
    type: 'Desk',
    feature: [''],
    color: ['Black'],
  },
  {
    category: 'lamp',
    name: 'Bonaffon',
    fullName: 'Bonaffon black lamp',
    productInfo:
      'Add a mid-century modern accent your desk or nightstand with the Bonaffon desk lamp. A convenient adjustable shade mixes walnut wood, antique brass and black metals to create a unique, functional style. A brass rotary switch on the base and a black and white fabric covered cord finish off this trend setting look.',
    img: 'https://i.ibb.co/48DN1qf/IMG-7174.jpg',
    price: 99,
    length: 510,
    switchType: ['Button'],
    type: 'Desk',
    feature: [''],
    color: ['Black'],
  },
  {
    category: 'lamp',
    name: 'Muuto',
    fullName: 'LED table lamp',
    productInfo:
      'Muuto is a minimalist aluminum piece smartly designed with high functionality. Its adjustable linear arms balance on top of each other, showcasing the tipping aspect of the piece. An adjustable laser cut lamp shade helps to produce a dimmable focused downlight and an ambient glow when its horizontal arm is angled upward. Its form factor embodies simplicity in a neat, sophisticated way.',
    img: 'https://i.ibb.co/RCq6vQP/IMG-7175.jpg',
    price: 469,
    length: 380,
    switchType: ['Button'],
    type: 'Desk',
    feature: [''],
    color: ['Black'],
  },
  {
    category: 'lamp',
    name: 'Nymane',
    fullName: 'Task lamp/wall light',
    productInfo:
      "Double function: to be used as a work lamp or to be fixed to the wall as a wall lamp. You can charge your mobile phone or other device using the lamp's built-in USB port. Provides a directed light beam perfect for reading. Easy to direct the light as needed thanks to the adjustable arm and swivel head.",
    img: 'https://i.ibb.co/nn3Lm9H/IMG-7177.jpg',
    price: 69,
    length: 620,
    switchType: ['Button'],
    type: 'Desk',
    feature: ['USB port'],
    color: ['White'],
  },
  {
    category: 'lamp',
    name: 'Southwold',
    fullName: 'Southwold mini table lamp',
    productInfo:
      'The White Company stylish mini table lamp is perfect for bedrooms, or living rooms – we love to place one either side of the bed, or sofa, for a beautifully symmetrical look. With a striking ceramic base that’s treated with a distressed grey-wash finish, it has a large cotton shade, which creates a warm, ambient glow when the light is on. Thanks to the hand-applied finish, slight variation may occur between each design, giving your lamp a unique, artisanal charm.',
    img: 'https://i.ibb.co/BHhjxVZ/IMG-7178.jpg',
    price: 92,
    length: 380,
    switchType: ['Button'],
    type: 'Bedside',
    feature: [''],
    color: ['White'],
  },
  {
    category: 'lamp',
    name: 'Kira',
    fullName: 'Touch control table lamp',
    productInfo:
      'The minimalist table lamp features a black nickel base and white open-top cylinder shade. Perfect for setting a relaxing mood and creating a comfortable living environment. The dimmable touch lamp provides a nice soft glow to the room and just enough light without blinding. Used well as a nightstand lamp, bedside table lamp, end table lamp and great for living room, bedroom, office, study room, nursery room or college dorm.',
    img: 'https://i.ibb.co/8BWdrkX/IMG-7179.jpg',
    price: 29,
    length: 445,
    switchType: ['Touch'],
    type: 'Bedside',
    feature: ['Brightness control'],
    color: ['White', 'Metallic'],
  },
  {
    category: 'lamp',
    name: 'Kizu',
    fullName: 'Kizu table lamp',
    productInfo:
      'Playing with shapes and materials, the Kizu table lamp spreads its soft light like an intriguing modern sculpture. The two opposing geometric shapes create the illusion that the light, in the acrylic lampshade, is floating above the beautiful marble base.',
    img: 'https://i.ibb.co/dGVrqxR/IMG-7180.jpg',
    price: 217,
    length: 350,
    switchType: ['Button'],
    type: 'Bedside',
    feature: [''],
    color: ['White'],
  },
  {
    category: 'lamp',
    name: 'Porfeet',
    fullName: 'Nightstand lamp with round base for home',
    productInfo:
      "Adopted retro style design making this product decorative and vintage, which has a fabric shade design. Featuring widely applied and multi-purpose, this product is suitable for decorating living room, bedroom, bedside, children's room, indoor lighting and so on. Made from bamboo and fabric material, this product is wear-resistant and decorative.",
    img: 'https://i.ibb.co/3f8hLc8/IMG-7182.jpg',
    price: 22,
    length: 260,
    switchType: ['Button'],
    type: 'Bedside',
    feature: ['USB port'],
    color: ['Brown'],
  },
  {
    category: 'lamp',
    name: 'Walm',
    fullName: 'Boho table lights for bedrooms',
    productInfo:
      'Retro and elegant bamboo woven table lamp to create a warm atmosphere,you can place it beside the bed as a night light.',
    img: 'https://i.ibb.co/48S86B7/IMG-7183.jpg',
    price: 65,
    length: 270,
    switchType: ['Button'],
    type: 'Bedside',
    feature: [''],
    color: ['Brown'],
  },
  {
    category: 'lamp',
    name: 'Versa',
    fullName: 'Bamboo table lamp',
    productInfo:
      'Bamboo is bang on trend and these beautiful boho style table lamps can work with lots of different shades to make it unique to your home. If you like a natural boho interior look, this is the product for you. Perfect lighting for the living room, dining room or as bedside lighting.',
    img: 'https://i.ibb.co/zR2Mpkj/IMG-7184.jpg',
    price: 103,
    length: 500,
    switchType: ['Button'],
    type: 'Bedside',
    feature: [''],
    color: ['Brown'],
  },
  {
    category: 'lamp',
    name: 'Upland',
    fullName: 'Upland circle natural lamp',
    productInfo:
      'The natural beauty of the geometric concrete base of the Upland Circle lampis paired with a white drum shade to provide any room with a touch of unrefined elegance.',
    img: 'https://i.ibb.co/RTBXH90/IMG-7185.jpg',
    price: 98,
    length: 610,
    switchType: ['Button'],
    type: 'Bedside',
    feature: [''],
    color: ['White'],
  },
  {
    category: 'lamp',
    name: 'Promenade',
    fullName: 'Promenade brass and glass table lamp with USB port',
    productInfo:
      'An illuminating mix of modern design and timeless craft, our Promenade table lamp showcases its warm, gleaming accents in a cylinder of hand-blown glass. Slim circles of brass-finished iron cap the tall, cylindrical base, and a white linen drum shade adds textural counterpoint. Designed for modern living, each lamp also features a handy USB port on the base to keep devices charged and ready.',
    img: 'https://i.ibb.co/L0LJw3s/IMG-7186.jpg',
    price: 199,
    length: 760,
    switchType: ['Button'],
    type: 'Bedside',
    feature: ['USB port'],
    color: ['White', 'Gold'],
  },
  {
    category: 'lamp',
    name: 'Adesso',
    fullName: 'Teardrop glass table lamp',
    productInfo:
      'Infuse a classic silhouette with boho texture when you light up your space with this rattan-shade table lamp. Featuring a teardrop-shaped glass base, topped by a wavy strand rattan shade. Plugs in to power on with rotary socket switch.',
    img: 'https://i.ibb.co/vVKbNJt/IMG-7187.jpg',
    price: 149,
    length: 585,
    switchType: ['Button'],
    type: 'Bedside',
    feature: [''],
    color: ['Brown'],
  },
  {
    category: 'lamp',
    name: 'Ore',
    fullName: 'Gold Metal White Glass Globe Table Lamp LED for Bedroom',
    productInfo:
      'This circle shape floor lamp provides a modern look for your home decoration. Put this upright, free-standing lamp beside a sofa or place it in your office next to the stately desk. Pair it with urban, contemporary, or modern decoration. Operated by a simple on/off switch, this lamp cast bright light throughout your space. A sleek gold frame paired with double glass shades, gives it an unobtrusive yet stylish look.',
    img: 'https://i.ibb.co/RpVTcKw/IMG-7188.jpg',
    price: 85,
    length: 520,
    switchType: ['Button'],
    type: 'Bedside',
    feature: [''],
    color: ['Gold'],
  },
  {
    category: 'lamp',
    name: 'Haitral',
    fullName: 'Haitral bedside table lamp',
    productInfo:
      'The white lamp is versatile lamp that be placed in any room one desires. It can offer bright enough to read under or for crafting if you’re thinking about using as a task light. It’s great to be used as reading lamp, office lamp, task lamp, nightstand table lamp, etc. Great a modern decoration for your home and office. Also, it’s a ideal gift for anyone!',
    img: 'https://i.ibb.co/NNQ50hT/IMG-7189.jpg',
    price: 53,
    length: 395,
    switchType: ['Pull chain'],
    type: 'Bedside',
    feature: [''],
    color: ['Gold', 'White'],
  },
  {
    category: 'lamp',
    name: 'Nala',
    fullName: 'Nala mango wood table lamp',
    productInfo:
      "With it's elegant curved base crafted from natural mango wood, the Nala Table lamp would make a gorgeous addition to any home décor styles. This stunning lamp features a global styling and comes complete with a linen fabric shade. This Nala Mango Wood Table Lamp complements an array of home decor with its contemporary design.",
    img: 'https://i.ibb.co/dr5CCtL/IMG-7190.jpg',
    price: 65,
    length: 400,
    switchType: ['Button'],
    type: 'Bedside',
    feature: [''],
    color: ['Beige', 'Brown'],
  },
  {
    category: 'lamp',
    name: 'Meco',
    fullName: 'Meco wall lamp',
    productInfo:
      'Like a eulogy to nature, mineral in raw sandstone, this new collection of lights is a trip to the west coast of Portugal, a cruise along its beaches between cliffs and fine sand dunes...',
    img: 'https://i.ibb.co/VJcgg6H/IMG-7191.jpg',
    price: 340,
    length: 200,
    switchType: ['Button'],
    type: 'Wall',
    feature: [''],
    color: ['Beige'],
  },
  {
    category: 'lamp',
    name: 'Corbel',
    fullName: 'Rustic wall light sconce',
    productInfo:
      'Interior wall lamp made with wood. Vintage style guaranteed, mood light with a vintage bulb or normal lighting with classic bulb. To put in an entrance, also at the head of the bed for a soft light, or in a living room.',
    img: 'https://i.ibb.co/nc94jyx/IMG-7192.jpg',
    price: 63,
    length: 300,
    switchType: ['Button'],
    type: 'Wall',
    feature: [''],
    color: ['Brown'],
  },
  {
    category: 'lamp',
    name: 'Reinar',
    fullName: 'Nordic modern style wall sconce',
    productInfo:
      'Wall lamp in modern style. Suitable as additional lighting for a separate area in a cafe / showroom / any room in your home. The sconce can be directed up or down.',
    img: 'https://i.ibb.co/Jx6ZPpT/IMG-7193.jpg',
    price: 266,
    length: 370,
    switchType: ['Button'],
    type: 'Wall',
    feature: [''],
    color: ['Blue', 'Gold'],
  },
  {
    category: 'lamp',
    name: 'Mobo',
    fullName: 'Mobo wall lamp',
    productInfo:
      "The Mobo's round shape adds a playful touch to the lamp's simple and calm design. The minimalist structure balances perfectly with the smooth curves and robustness of the handmade ceramic shade. Its structure (stem & arm) is available in brass or coated steel in stone colour, combined with an elegant oak detail.",
    img: 'https://i.ibb.co/12nhGzY/IMG-7194.jpg',
    price: 561,
    length: 520,
    switchType: ['Button'],
    type: 'Wall',
    feature: [''],
    color: ['Green', 'Gold'],
  },
  {
    category: 'lamp',
    name: 'Cast',
    fullName: 'Cast sconce wall lamp with diffuser',
    productInfo:
      'The Cast sconce wall lamp unites triangular, linear and round elements into a sophisticated silhouette. Purposeful and with presence, its geometric form adds to the ambience of a room both when turned on and off. The LED light is controlled by a dimmer switch on the cord. The thoughtfully designed brushed brass arm, cast aluminium shade and corresponding mounting plate create an engaging form that naturally assimilates into the design of any room.',
    img: 'https://i.ibb.co/HHc4hnQ/IMG-7195.jpg',
    price: 240,
    length: 190,
    switchType: ['Button'],
    type: 'Wall',
    feature: [''],
    color: ['Black'],
  },
  {
    category: 'lamp',
    name: 'Nordic',
    fullName: 'Nordic wall lamp',
    productInfo:
      'This is a minimalist wall lamp with a modern style that will bring a unique charm and pleasant lighting to any room.',
    img: 'https://i.ibb.co/TYQ2dRX/IMG-7196.jpg',
    price: 140,
    length: 380,
    switchType: ['Button'],
    type: 'Wall',
    feature: [''],
    color: ['Gold'],
  },
  {
    category: 'lamp',
    name: 'Gling',
    fullName: 'Light nordic style dimmable wall lamp',
    productInfo:
      'LED wall light creates a warm environment atmosphere for your house, making it a perfect decorative accent and sleeping light. Ideal for living room, dining room, bedroom, kids study room, kitchen island, hallway, office and more.',
    img: 'https://i.ibb.co/CwrZhrc/IMG-7197.jpg',
    price: 60,
    length: 240,
    switchType: ['Remote'],
    type: 'Wall',
    feature: ['Brightness control'],
    color: ['Black'],
  },
  {
    category: 'lamp',
    name: 'Fillini',
    fullName: 'Rod wall lamp',
    productInfo:
      'Fillini are trendy luminaires for creating unusual scenarios with reflected light, which are especially relevant for interiors where textured surfaces are actively used, requiring a special approach to lighting. Thin black silhouettes of wall lamps will look unforgettable and spectacular in the composition. (Set of 2)',
    img: 'https://i.ibb.co/68XjBRJ/IMG-7199.jpg',
    price: 326,
    length: 1000,
    switchType: ['Button'],
    type: 'Wall',
    feature: [''],
    color: ['Black'],
  },
  {
    category: 'lamp',
    name: 'Slimpeace',
    fullName: 'Minimalist wooden linear wall lamp',
    productInfo:
      'This simple and minimalist lamp gives ambient light to your wall. Its universal design allows it to be combined with many styles. The lamp can be mounted vertically and horizontally. The wooden housing is held on the metal frame by magnets.',
    img: 'https://i.ibb.co/yQv4wn1/IMG-7200.jpg',
    price: 227,
    length: 1000,
    switchType: ['Button'],
    type: 'Wall',
    feature: [''],
    color: ['Brown'],
  },
  {
    category: 'lamp',
    name: 'Skaftet',
    fullName: 'Curved arch floor lamp',
    productInfo:
      'This splendid neo-retro design arc floor lamp brings stability and elegance that will perfectly illuminate your interior. Its lampshade offsets the light source while leaving free space to showcase your most beautiful furniture. This floor lamp will become an essential and structuring piece in your living room.',
    img: 'https://i.ibb.co/1TwtyPv/IMG-7201.jpg',
    price: 97,
    length: 1830,
    switchType: ['Button'],
    type: 'Floor',
    feature: [''],
    color: ['Black', 'Beige'],
  },
  {
    category: 'lamp',
    name: 'Ornado',
    fullName: 'Ornado black floor lamp',
    productInfo:
      'Tripod silhouette in solid iron is an updated Nicholas Obeid design, complete with bracket detailing that extends out to hug the raw silk shade. Floor lamp has a soft glow with a black powdercoated finish to edge up its simplistic form.',
    img: 'https://i.ibb.co/gWD7ddv/IMG-7204.jpg',
    price: 249,
    length: 1425,
    switchType: ['Button'],
    type: 'Floor',
    feature: [''],
    color: ['Black', 'Beige'],
  },
  {
    category: 'lamp',
    name: 'Rigel',
    fullName: 'Rigel floor lamp',
    productInfo:
      'Like a luminous and transparent petal, this floor lamp has an organic design while offering real technological prowess. The central source located on the petal-shaped diffuser diffuses a bright central and edge light. A dimmer will allow you to adjust the light intensity according to the desired atmosphere.',
    img: 'https://i.ibb.co/HnWr4r3/IMG-7205.jpg',
    price: 347,
    length: 1950,
    switchType: ['Button', 'Remote'],
    type: 'Floor',
    feature: ['Brightness control'],
    color: ['Black'],
  },
  {
    category: 'lamp',
    name: 'Verde',
    fullName: 'Verde dimmable LED floor lamp',
    productInfo:
      'This floor lamp emanates a sprightly ambiance, sending forth a burst of fresh breath. It provides two glass planters so that you can sprout ornamental plants. Home horticulture charms with vivacity amongst the urban mundane. It comes with a remote control so you can save electricity. Great for homeowners who practice sustainability.',
    img: 'https://i.ibb.co/ZNj6xWS/IMG-7207.jpg',
    price: 214,
    length: 1250,
    switchType: ['Button', 'Remote'],
    type: 'Floor',
    feature: ['Brightness control'],
    color: ['Black'],
  },
  {
    category: 'lamp',
    name: 'Ozz',
    fullName: 'Ozz floor lamp',
    productInfo:
      'Ozz works in several ways. From a shape reminiscent of a tuning fork, two elements develop, a lamp and a tray of objects, which look at each other and dialogue with a clearly defined rhythm: the rhythm of light. If when switched off Ozz functions as a small table, when switched on envelops the top creating a welcoming and intimate space.',
    img: 'https://i.ibb.co/8MZS7ZD/IMG-7210.jpg',
    price: 1029,
    length: 1510,
    switchType: ['Pull chain'],
    type: 'Floor',
    feature: [''],
    color: ['Black'],
  },
  {
    category: 'lamp',
    name: 'Aveo',
    fullName: 'Asymmetry ceramic table lamp',
    productInfo:
      "The unique, organically shaped base. It's topped with a pure linen shade. Offers an ambient diffused light. An asymmetrical ceramic base takes its cues from Japanese pottery.",
    img: 'https://i.ibb.co/5MDSLtt/IMG-7252.jpg',
    price: 149,
    length: 430,
    switchType: ['Button'],
    type: 'Bedside',
    feature: [''],
    color: ['Beige', 'Green'],
  },
];
