import { Shelves } from '../interfaces/shelves-interface';

export const shelves: Shelves[] = [
  {
    category: 'shelf',
    name: 'Umsy',
    fullName: 'Umzy wall mounted shelves (set of 4)',
    productInfo:
      'Our individual beech pyramid shelves are designed in the UK and lovingly handmade from beech wood. Each natural color hook is finished with a natural oil to bring out the natural beauty of the wood grain and protect it from damage.',
    img: 'https://i.ibb.co/gTgYRGp/IMG-7219.jpg',
    price: 162,
    length: 1120,
    numberOfShelves: 4,
    type: 'Wall',
    feature: '',
    shape: 'Triangular',
    color: ['Wood'],
  },
  {
    category: 'shelf',
    name: 'Rustic',
    fullName: 'Rustic wooden wall shelf',
    productInfo:
      'The wood shelves with the iron brackets create a rustic feel yet can work with many decor styles.',
    img: 'https://i.ibb.co/ZXbJxKh/IMG-7220.jpg',
    price: 95,
    length: 860,
    numberOfShelves: 1,
    type: 'Wall',
    feature: '',
    shape: 'Rectangular',
    color: ['Wood'],
  },
  {
    category: 'shelf',
    name: 'Link',
    fullName: 'Shelving system Link',
    productInfo:
      'The LINK-shelf is display and storage stripped down to the essentials. Its steel and wood construction forms an engaging interplay with many potential compositions: asymmetrical, high-reaching, or laid out lengthwise, the LINK-shelf is designed to work perfectly for your individual environment. The LINK shelving system lets you get back to the basic pleasure of creating your space.',
    img: 'https://i.ibb.co/kqWTXGJ/IMG-7221.jpg',
    price: 349,
    length: 1190,
    numberOfShelves: 4,
    type: 'Wall',
    feature: '',
    shape: 'Rectangular',
    color: ['White'],
  },
  {
    category: 'shelf',
    name: 'Honey',
    fullName: 'Set of 6 hexagon honeycomb shelves',
    productInfo:
      'Shelves are hung individually, and can be hung in whichever pattern you\'d like! They have been sanded down once to remove splintering wood, but not too much so they still have the "reclaimed" look.',
    img: 'https://i.ibb.co/kyZ8r5H/IMG-7222.jpg',
    price: 408,
    length: 1830,
    numberOfShelves: 6,
    type: 'Wall',
    feature: '',
    shape: 'Other',
    color: ['Wood'],
  },
  {
    category: 'shelf',
    name: 'Moon',
    fullName: 'Crescent shaped wall shelving',
    productInfo:
      'We’re over the moon for this carved wood wall shelf in the shape of a crescent moon. With four petite shelves, it’s perfect for holding all your favorite little finds.',
    img: 'https://i.ibb.co/31mFJZ8/IMG-7223.jpg',
    price: 99,
    length: 508,
    numberOfShelves: 4,
    type: 'Wall',
    feature: '',
    shape: 'Other',
    color: ['Wood'],
  },
  {
    category: 'shelf',
    name: 'Bodhi',
    fullName: 'Wooden wall rack',
    productInfo:
      'This wall rack has a modern and stylish look. The wall rack is not only beautiful to look at, but also very functional. Ideal for storing or displaying small items. Think, for example, of a small (herb) plant, a beautiful vase or another stylish item.',
    img: 'https://i.ibb.co/M1FLpzG/IMG-7225.jpg',
    price: 57,
    length: 920,
    numberOfShelves: 3,
    type: 'Wall',
    feature: '',
    shape: 'Rectangular',
    color: ['Wood'],
  },
  {
    category: 'shelf',
    name: 'Cubby',
    fullName: 'Rustic metal shelves',
    productInfo:
      "The shelf's interesting design adds a touch of whimsy to the otherwise drab space and brings some style and style to whatever room it's in. Don't worry about it falling off - you can easily place it on the nearby wall.",
    img: 'https://i.ibb.co/sHM4nn2/IMG-7226.jpg',
    price: 277,
    length: 550,
    numberOfShelves: 3,
    type: 'Wall',
    feature: '',
    shape: 'Rectangular',
    color: ['Black'],
  },
  {
    category: 'shelf',
    name: 'Laos',
    fullName: 'Triangle wall-mount shelf',
    productInfo:
      'Triangular wall shelves made of wood will fit into any interior.',
    img: 'https://i.ibb.co/wdQ6CDB/IMG-7227.jpg',
    price: 92,
    length: 610,
    numberOfShelves: 2,
    type: 'Wall',
    feature: '',
    shape: 'Triangular',
    color: ['Wood'],
  },
  {
    category: 'shelf',
    name: 'Bridge',
    fullName: 'Hanging shelf Bridge',
    productInfo:
      'The Bridge shelf consists of four parts made of oak: a crossbar and three shelves of different lengths. On the crossbar, the shelves are held with curved metal rods and can be moved to different sides, adjusting to the contents.',
    img: 'https://i.ibb.co/b5ggRLj/IMG-7228.jpg',
    price: 36,
    length: 620,
    numberOfShelves: 3,
    type: 'Wall',
    feature: '',
    shape: 'Rectangular',
    color: ['Wood'],
  },
  {
    category: 'shelf',
    name: 'Idea',
    fullName: 'Wall hanging module Idea',
    productInfo:
      'This shelf is designed to hold oversized books, file folders, and anything else that can fit in it.',
    img: 'https://i.ibb.co/Dfj60Pm/IMG-7229.jpg',
    price: 33,
    length: 200,
    numberOfShelves: 1,
    type: 'Wall',
    feature: '',
    shape: 'Rectangular',
    color: ['Blue'],
  },
  {
    category: 'shelf',
    name: 'Eket',
    fullName: 'Wall shelf combination',
    productInfo:
      'Eket wall shelf allows you to save floor space and make the most of the wall. Combine open and closed storage as needed. The asymmetrical arrangement of the sections will emphasize the individuality of the storage solution.',
    img: 'https://i.ibb.co/hCs4sRf/IMG-7230.jpg',
    price: 218,
    length: 1350,
    numberOfShelves: 4,
    type: 'Wall',
    feature: '',
    shape: 'Rectangular',
    color: ['Black', 'Pink'],
  },
  {
    category: 'shelf',
    name: 'Alta',
    fullName: 'Alta wall shelf set',
    productInfo:
      'Alta wall shelf set - a set of three shelves with a decorated metal back. Shelves of different sizes can be placed on the wall in any order. Convenient and functional products will help to arrange a lot of things and give the room a more comfortable look.',
    img: 'https://i.ibb.co/2dxSbKv/IMG-7231.jpg',
    price: 23,
    length: 1050,
    numberOfShelves: 3,
    type: 'Wall',
    feature: '',
    shape: 'Rectangular',
    color: ['Black', 'Wood'],
  },
  {
    category: 'shelf',
    name: 'Nook',
    fullName: 'Reclaimed barn wood floating accent shelves',
    productInfo:
      'This shelves can be mounted on any home or office wall. Works as an organizer for gadgets and kitchen spices, or as a bookshelf in the living room. Use to showcase your photos, plants and trophies.',
    img: 'https://i.ibb.co/c2hNfcJ/IMG-7232.jpg',
    price: 107,
    length: 920,
    numberOfShelves: 2,
    type: 'Wall',
    feature: '',
    shape: 'Rectangular',
    color: ['Wood'],
  },
  {
    category: 'shelf',
    name: 'Cole',
    fullName: 'Natural wall mounted hanging storage shelf with 6 metal hooks',
    productInfo:
      'The wall shelf with coat rack will be a great choice to add greater convenience and extra storage. This design features sturdy metal hooks mounted on a durable wood base, an engaging style for your existing interior decoration. The handy hooked rack can be used to hang articles of clothing, jackets, scarves, towels, and more while the top shelf creates a spot for displaying or storing any accessories. A great addition to your entryway, foyer, living room, and bedroom.',
    img: 'https://i.ibb.co/yd6jPP8/IMG-7233.jpg',
    price: 58,
    length: 765,
    numberOfShelves: 1,
    type: 'Wall',
    feature: 'With hooks',
    shape: 'Rectangular',
    color: ['Wood'],
  },
  {
    category: 'shelf',
    name: 'Unmbo',
    fullName: 'Unmbo wood floating shelves',
    productInfo:
      'The simple design floating shelves constructed of wood boards and metal brackets, perfect for displaying and holding collectibles, small plants, stuffed animals and more.',
    img: 'https://i.ibb.co/XpVRx2n/IMG-7235.jpg',
    price: 73,
    length: 460,
    numberOfShelves: 1,
    type: 'Wall',
    feature: 'With hooks',
    shape: 'Rectangular',
    color: ['Wood'],
  },
  {
    category: 'shelf',
    name: 'Homode',
    fullName: 'Homode coat rack with shelf',
    productInfo:
      'Wall mounted coat hook with shelf offers display and storage options wherever they need it most. Keep your places neat and organized in entryway, laundry room, mudroom, kitchen, bathroom. Top shelf creates a display area for a potted plant, small decorative pieces, especially to display photo frames as the groove design prevents it from slipping down.',
    img: 'https://i.ibb.co/jV98Lq6/IMG-7234.jpg',
    price: 49,
    length: 765,
    numberOfShelves: 1,
    type: 'Wall',
    feature: 'With hooks',
    shape: 'Rectangular',
    color: ['Wood'],
  },
  {
    category: 'shelf',
    name: 'Brighton',
    fullName: 'Brighton closet shelf with rail',
    productInfo:
      'Embrace the versatility of open shelving. Crafted of substantial mango wood planks, Brighton adds a warmth to walls. Curate a well-styled entryway or display dinnerware and mugs in the kitchen (kitchen hooks will come in handy). Short on closet space? This is a beautiful way to hang up your wardrobe.',
    img: 'https://i.ibb.co/yd7xWMx/IMG-7236.jpg',
    price: 349,
    length: 1220,
    numberOfShelves: 1,
    type: 'Wall',
    feature: 'With rail',
    shape: 'Rectangular',
    color: ['Wood'],
  },
  {
    category: 'shelf',
    name: 'Crakth',
    fullName: 'Key Hooks & Shelf',
    productInfo:
      'This pine wood round is stained and hand painted. Three gold hooks are attached- perfect for keys, mask, or any other essential for running out the door. The small shelf is perfect for a plant or sunglasses.',
    img: 'https://i.ibb.co/GM6M8SR/IMG-7237.jpg',
    price: 38,
    length: 305,
    numberOfShelves: 1,
    type: 'Wall',
    feature: 'With hooks',
    shape: 'Rounded',
    color: ['Wood', 'Green'],
  },
  {
    category: 'shelf',
    name: 'Utex',
    fullName: '3-tier bathroom ladder shelf',
    productInfo:
      'This 3-tier bathroom ladder shelf is the perfect storage option for your bathroom. Each shelf is wide, providing that much-needed space in any room, side and back support panel prevents items from falling out and keeps things upright.',
    img: 'https://i.ibb.co/wNmJfRK/IMG-7239.jpg',
    price: 94,
    length: 450,
    numberOfShelves: 3,
    type: 'Floor',
    feature: '',
    shape: 'Rectangular',
    color: ['White'],
  },
  {
    category: 'shelf',
    name: 'Bronx',
    fullName: 'Bronx ladder shelf',
    productInfo:
      'The most stylish and convenient solution for storing small items is a loft-style ladder shelf. Especially popular for the bath!',
    img: 'https://i.ibb.co/NVtwftp/IMG-7240.jpg',
    price: 232,
    length: 500,
    numberOfShelves: 5,
    type: 'Floor',
    feature: '',
    shape: 'Rectangular',
    color: ['Wood'],
  },
  {
    category: 'shelf',
    name: 'Ato',
    fullName: 'Ato geometric bookcase',
    productInfo:
      'This 9-Shelf Tree Magazine CD Geometric Bookcase is durable enough to hold plenty of stackable books, magazines, or trinkets. For those book lovers, this product will keep reading material neatly coordinated, super accessible, and uniquely displayed. In an office setting, the shelves can be piled with files, books, or office decor.',
    img: 'https://i.ibb.co/R7brbbQ/IMG-7241.jpg',
    price: 243,
    length: 1400,
    numberOfShelves: 9,
    type: 'Floor',
    feature: '',
    shape: 'Other',
    color: ['White'],
  },
  {
    category: 'shelf',
    name: 'Vega',
    fullName: 'Vega metal corner bookcase',
    productInfo:
      'A practical shelf can freshen up your room in every respect. This bookcase is friendly for compact spaces such as the kitchen, study, living room, bedroom, and so on. This storage shelf is durable and stable because of the premium chipboard and metal material.',
    img: 'https://i.ibb.co/SrKYwsS/IMG-7243.jpg',
    price: 65,
    length: 1245,
    numberOfShelves: 4,
    type: 'Floor',
    feature: '',
    shape: 'Other',
    color: ['Wood', 'Black'],
  },
  {
    category: 'shelf',
    name: 'Karonda',
    fullName: 'Bamboo multi-functional storage shelf',
    productInfo:
      '5-tier rack features sturdy bamboo and refined craft, creating additional space to your home, it offers stylish design and plenty of display options. The solid natural bamboo construction has a sleek, environmental protection varnish finish to coordinate with any decor.  It can be used as a storage rack for toiletries, towels, sundries, decorative things, knick knacks, shoes, plants, spice and small appliances.',
    img: 'https://i.ibb.co/Vw5kGvp/IMG-7245.jpg',
    price: 129,
    length: 1280,
    numberOfShelves: 5,
    type: 'Floor',
    feature: '',
    shape: 'Rectangular',
    color: ['Wood'],
  },
];
