import { Tables } from '../interfaces/tables-interface';

export const tables: Tables[] = [
  {
    category: 'table',
    name: 'Mango',
    fullName: 'The Urban Port Mango Wood Coffee Table in Round Shape',
    productInfo:
      'Features Dark Brown finish and a wide table top that allows you to keep many things on it. Elegantly designed table by expert artists in drum shape is made up of mango wood. Can be used as a center table for serving evening tea, coffee or snacks. This table can be used for personal and commercial purpose as it is ideal for indoors.',
    img: 'https://i.ibb.co/KmqZyjM/IMG-7125.jpg',
    price: 389,
    length: 900,
    width: 900,
    height: 500,
    type: 'Coffee',
    shape: 'Rounded',
    color: ['White'],
  },
  {
    category: 'table',
    name: 'Hokitika',
    fullName: 'Hokitika coffee table',
    productInfo:
      'Coffee table incorporates a powder-coated frame with a sleek wooden tabletop to create an understated modern industrial design. Featuring smooth metal contrasted by natural wood, this table offers a chic aesthetic to any home.',
    img: 'https://i.ibb.co/WgKRrTL/IMG-7124.jpg',
    price: 589,
    length: 910,
    width: 910,
    height: 480,
    type: 'Coffee',
    shape: 'Rounded',
    color: ['Wood'],
  },
  {
    category: 'table',
    name: 'Throm',
    fullName: 'Lifting coffee table with drawer',
    productInfo:
      'Offering a lift top and drawer, this Throm coffee table is convenient and practical. The lift top gives you more freedom and convenience. Enhancing your relaxing experience in front of the TV. The hidden storage compartment underneath makes it user-friendly in a variety of different contexts. Featuring a weathered oak finish and a classic design, it will fit in variety of living room aesthetics.',
    img: 'https://i.ibb.co/JzxXmdf/IMG-7123.jpg',
    price: 319,
    length: 1220,
    width: 585,
    height: 460,
    type: 'Coffee',
    shape: 'Rectangular',
    color: ['Wood'],
  },
  {
    category: 'table',
    name: 'Entu',
    fullName: 'Entu coffee table',
    productInfo:
      'Entu Coffee Table for your modern Living Room include extra space for your books.',
    img: 'https://i.ibb.co/DgwkH8R/IMG-7122.jpg',
    price: 429,
    length: 1200,
    width: 600,
    height: 400,
    type: 'Coffee',
    shape: 'Rectangular',
    color: ['Wood'],
  },
  {
    category: 'table',
    name: 'Malcolm',
    fullName: 'Malcolm round nesting coffee tables',
    productInfo:
      'Expertly crafted of spruce, the rustic look of the wood contrasts handsomely with a modern metal base. Ideal for multi-use rooms, it extends your surface area when needed, then quickly tucks in when not in use. The open design is perfect for a storage basket, making unused space extra functional.',
    img: 'https://i.ibb.co/J3YTYGX/IMG-7121.jpg',
    price: 1398,
    length: 1015,
    width: 1015,
    height: 480,
    type: 'Coffee',
    shape: 'Rounded',
    color: ['Wood'],
  },
  {
    category: 'table',
    name: 'Solstice',
    fullName: 'Solstice coffee tables',
    productInfo:
      'Each table flows seamlessly from the top to the sides for a waterfall effect.',
    img: 'https://i.ibb.co/bXVYdj3/IMG-7120.jpg',
    price: 599,
    length: 1115,
    width: 560,
    height: 305,
    type: 'Coffee',
    shape: 'Rectangular',
    color: ['White'],
  },
  {
    category: 'table',
    name: 'Nordic',
    fullName: 'Modern round nesting 2-piece extendable coffee table',
    productInfo:
      'Featuring an open nesting design and circular silhouettes, this side table is a characteristic and eye-catching addition to fit into most of home decor. With the extendable design,, it not only creates a chic look, but also offers extra space to hold your living essentials. If it is no need, just tuck the small piece under its companion to reclaim your floor space.',
    img: 'https://i.ibb.co/cxrF4V7/IMG-7119.jpg',
    price: 459,
    length: 1200,
    width: 1200,
    height: 350,
    type: 'Coffee',
    shape: 'Rounded',
    color: ['White', 'Black'],
  },
  {
    category: 'table',
    name: 'Cuba',
    fullName: 'Cuba round coffee table',
    productInfo:
      'The Cuba coffee table is a timeless and contemporary statement for your lounge room with a circular teak wood top and core rattan bottom.',
    img: 'https://i.ibb.co/z4yhp29/IMG-7118.jpg',
    price: 400,
    length: 750,
    width: 750,
    height: 320,
    type: 'Coffee',
    shape: 'Rounded',
    color: ['White'],
  },
  {
    category: 'table',
    name: 'Folsom',
    fullName: 'Folsom rectangular coffee table',
    productInfo:
      'Folsom feels substantial not heavy, and works hard while looking effortless. The open design leaves space for inspired styling.',
    img: 'https://i.ibb.co/xg3vBhY/IMG-7117.jpg',
    price: 799,
    length: 1475,
    width: 610,
    height: 470,
    type: 'Coffee',
    shape: 'Rectangular',
    color: ['White'],
  },
  {
    category: 'table',
    name: 'Westelm',
    fullName: 'Storage coffee table',
    productInfo:
      'The Mid-Century Living Room Collection borrows its tapered legs, angled face and understated details from iconic 50s and 60s furniture design. Two drawers open on metal glides; one open shelf.',
    img: 'https://i.ibb.co/9NPCJFp/IMG-7116.jpg',
    price: 599,
    length: 1195,
    width: 560,
    height: 435,
    type: 'Coffee',
    shape: 'Rectangular',
    color: ['Wood'],
  },
  {
    category: 'table',
    name: 'Asher',
    fullName: 'Asher coffee table',
    productInfo:
      'Raised edge top is both stylish & functional. Subtly slanted tapered legs steal the show. Compact yet durable, this sturdy table is just the right scale for tighter rooms.',
    img: 'https://i.ibb.co/g7rcbDZ/IMG-7115.jpg',
    price: 199,
    length: 710,
    width: 710,
    height: 380,
    type: 'Coffee',
    shape: 'Rounded',
    color: ['Wood'],
  },
  {
    category: 'table',
    name: 'Chadwick',
    fullName: 'Chadwick mid-century rectangle coffee table',
    productInfo:
      'Textural woven shelf adds natural elegance. Rich walnut finish goes with anything. Subtly rounded edges and tapered legs give it a minimalist mid-century modern look.',
    img: 'https://i.ibb.co/94sNftQ/IMG-7113.jpg',
    price: 479,
    length: 1220,
    width: 560,
    height: 405,
    type: 'Coffee',
    shape: 'Rectangular',
    color: ['Wood'],
  },
  {
    category: 'table',
    name: 'Accent',
    fullName: 'Accent coffee table',
    productInfo:
      'The coffee table is a collection perfect for a variety of rooms at home. It gives you plenty of surface space to spread out the evening news, host your guests drinks, place your drinks, vases, fruit bowls or ornaments.',
    img: 'https://i.ibb.co/SPWBv60/IMG-7112.jpg',
    price: 319,
    length: 600,
    width: 600,
    height: 400,
    type: 'Coffee',
    shape: 'Rounded',
    color: ['White'],
  },
  {
    category: 'table',
    name: 'Domus',
    fullName: 'Desk Domus',
    productInfo:
      'The table is perfect for almost any interior, as it is quite versatile. Straight lines and notes of geometry will give the room freedom of space. Such a table will definitely attract attention and add zest to your interior.',
    img: 'https://i.ibb.co/stK7cQg/IMG-7111.jpg',
    price: 496,
    length: 900,
    width: 660,
    height: 750,
    type: 'Desk',
    shape: 'Rectangular',
    color: ['White', 'Wood'],
  },
  {
    category: 'table',
    name: 'Jasper',
    fullName: 'Computer table with painted MDF fronts',
    productInfo: 'Computer table with painted MDF fronts.',
    img: 'https://i.ibb.co/z5nCQHX/IMG-7110.jpg',
    price: 829,
    length: 1200,
    width: 600,
    height: 750,
    type: 'Desk',
    shape: 'Rectangular',
    color: ['White', 'Black'],
  },
  {
    category: 'table',
    name: 'Keypiece',
    fullName: 'Keypiece communication desk',
    productInfo:
      'The design of the Keypiece table meets the demands of modern business routine, including working, consulting, meeting and video conferencing.',
    img: 'https://i.ibb.co/TrCh8Df/IMG-7109.jpg',
    price: 1249,
    length: 2300,
    width: 900,
    height: 750,
    type: 'Desk',
    shape: 'Rectangular',
    color: ['White', 'Wood'],
  },
  {
    category: 'table',
    name: 'Tribesigns',
    fullName: 'Tribesigns computer desk with file drawer and storage shelf',
    productInfo:
      'Space-saving whilst still providing you with plenty of room for gaming, handcrafting, studying, working and other desktop activities!',
    img: 'https://i.ibb.co/mzYQmNW/IMG-7108.jpg',
    price: 725,
    length: 1500,
    width: 600,
    height: 860,
    type: 'Desk',
    shape: 'Rectangular',
    color: ['Wood'],
  },
  {
    category: 'table',
    name: 'Crafto',
    fullName: 'Modular desks Crafto',
    productInfo: 'Laconic writing desk for your creativity.',
    img: 'https://i.ibb.co/48Zh4z3/IMG-7107.jpg',
    price: 369,
    length: 1100,
    width: 600,
    height: 750,
    type: 'Desk',
    shape: 'Rectangular',
    color: ['White', 'Wood'],
  },
  {
    category: 'table',
    name: 'Sheesham',
    fullName: 'Wave solid sheesham wood two drawer desk/study table',
    productInfo:
      'Desk in a trendy retro look. Generous table top for comfortable working at the table. Enough storage space thanks to a drawer and a storage compartment.',
    img: 'https://i.ibb.co/kJzfmq8/IMG-7106.jpg',
    price: 519,
    length: 1170,
    width: 560,
    height: 760,
    type: 'Desk',
    shape: 'Rectangular',
    color: ['Wood'],
  },
  {
    category: 'table',
    name: 'Elephant',
    fullName: 'Height adjustable live edge standing desk',
    productInfo:
      "Set your ergonomic height and switch from sit to stand at desk with a push of a tactile button. Stability and practicality are the top priorities of Elephant Desks' height adjustable frames and controls.",
    img: 'https://i.ibb.co/wMxKJGv/IMG-7105.jpg',
    price: 1099,
    length: 1520,
    width: 680,
    height: 1200,
    type: 'Desk',
    shape: 'Rectangular',
    color: ['Wood'],
  },
  {
    category: 'table',
    name: 'Nexus',
    fullName: 'Desk loft Nexus',
    productInfo:
      'Desk Loft NEXUS - a modern table for a laptop or computer in the LOFT style, on supports made of aluminum profile pipes with three drawers and a secret compartment.',
    img: 'https://i.ibb.co/f0ycZzj/IMG-7104.jpg',
    price: 396,
    length: 1200,
    width: 700,
    height: 750,
    type: 'Desk',
    shape: 'Rectangular',
    color: ['Wood'],
  },
  {
    category: 'table',
    name: 'Verdy',
    fullName:
      'White rectangular writing desk computer desk with shelf & drawer',
    productInfo:
      'This computer table with drive shelves and drawer is for your place to store even documents, books, wires, and other items are neatly kept in a drawer and on a shelf in the corner.',
    img: 'https://i.ibb.co/PZm76Qz/IMG-7103.jpg',
    price: 439,
    length: 1200,
    width: 600,
    height: 750,
    type: 'Desk',
    shape: 'Rectangular',
    color: ['White'],
  },
  {
    category: 'table',
    name: 'Diamur',
    fullName: 'Diamur concept wooden desk',
    productInfo:
      'Its simplicity and its small size let it integrate in any kind of home or hotel environment and the subtle details make this piece elegant and timeless.',
    img: 'https://i.ibb.co/HKRm5DX/IMG-7102.jpg',
    price: 179,
    length: 900,
    width: 600,
    height: 750,
    type: 'Desk',
    shape: 'Rectangular',
    color: ['Wood'],
  },
  {
    category: 'table',
    name: 'Elegance',
    fullName: 'Office table Elegance',
    productInfo:
      'An office table in a modern style will become an excellent element of your workspace. The table is white, single. Marble table top.',
    img: 'https://i.ibb.co/Fkr84yY/IMG-7101.jpg',
    price: 972,
    length: 1400,
    width: 710,
    height: 750,
    type: 'Desk',
    shape: 'Rounded',
    color: ['White'],
  },
  {
    category: 'table',
    name: 'Kitt',
    fullName: 'Kitt desk',
    productInfo: 'Creative home office desk for the urban living.',
    img: 'https://i.ibb.co/LvbwFNF/IMG-7100.jpg',
    price: 209,
    length: 1000,
    width: 600,
    height: 750,
    type: 'Desk',
    shape: 'Rectangular',
    color: ['Wood'],
  },
  {
    category: 'table',
    name: 'Oak',
    fullName: 'Round dining table',
    productInfo:
      'A little dining room area can look comfortable while in the meantime give a place to appreciate a pleasant dinner with companions or family. It can even be utilized once a day to make mealtime with your close family an exceptional time.',
    img: 'https://i.ibb.co/2nx99Dk/IMG-7099.jpg',
    price: 179,
    length: 900,
    width: 900,
    height: 750,
    type: 'Dining',
    shape: 'Rounded',
    color: ['Wood'],
  },
  {
    category: 'table',
    name: 'Vitra',
    fullName: 'Round wooden dining table with one leg',
    productInfo:
      'A round wooden table on one leg is both aesthetically pleasing, comfortable and functional.',
    img: 'https://i.ibb.co/KrmTCjR/IMG-7098.jpg',
    price: 426,
    length: 1000,
    width: 1000,
    height: 750,
    type: 'Dining',
    shape: 'Rounded',
    color: ['Wood'],
  },
  {
    category: 'table',
    name: 'Farmhouse',
    fullName: 'Dining table Farmhouse',
    productInfo:
      'This piece of furniture is made in a classic design, has a massive countertop and supports. In the manufacture of the Farmhouse dining table, an array of hardwood, veneered MDF is used.',
    img: 'https://i.ibb.co/ftVwy5F/IMG-7097.jpg',
    price: 1199,
    length: 2400,
    width: 960,
    height: 760,
    type: 'Dining',
    shape: 'Rectangular',
    color: ['Wood'],
  },
  {
    category: 'table',
    name: 'Rustic',
    fullName: 'Rustic wooden dining table with glass top',
    productInfo:
      'Instead of being polished or traditional, rustic wooden tables appear inviting and appealing. They have a natural, organic appearance that will welcome your visitors. These dining tables complement a rustic interior design scheme effectively.',
    img: 'https://i.ibb.co/LvZr0hf/IMG-7096.jpg',
    price: 1469,
    length: 2600,
    width: 1080,
    height: 760,
    type: 'Dining',
    shape: 'Rectangular',
    color: ['Wood'],
  },
  {
    category: 'table',
    name: 'Vega',
    fullName: 'Dining table Vega',
    productInfo:
      'This table will create an attractive accent in your environment. Every detail is thought out for trifles, because the decor perfectly complements the image of a modern dining room.',
    img: 'https://i.ibb.co/tcJZY0s/IMG-7093.jpg',
    price: 889,
    length: 2200,
    width: 1000,
    height: 750,
    type: 'Dining',
    shape: 'Rectangular',
    color: ['Wood'],
  },
  {
    category: 'table',
    name: 'Bagli',
    fullName: 'Dining table Bagli',
    productInfo:
      'The dining table is made of Indian rosewood (rosewood). The legs are metal.',
    img: 'https://i.ibb.co/g3YDjdD/IMG-7092.jpg',
    price: 386,
    length: 1200,
    width: 800,
    height: 760,
    type: 'Dining',
    shape: 'Rectangular',
    color: ['Wood'],
  },
  {
    category: 'table',
    name: 'Liveco',
    fullName: 'Dining table Liveco',
    productInfo:
      'The table is perfect for a spacious kitchen, but at the same time it will not look unnecessarily cumbersome due to the simple and concise design, which gives the table lightness and airiness.',
    img: 'https://i.ibb.co/y5dtBp2/IMG-7091.jpg',
    price: 298,
    length: 1600,
    width: 900,
    height: 760,
    type: 'Dining',
    shape: 'Rectangular',
    color: ['Wood'],
  },
  {
    category: 'table',
    name: 'Eligard',
    fullName: 'Dining table Eligard',
    productInfo:
      'A simple table in Scandinavian style will fit perfectly into any modern interior.',
    img: 'https://i.ibb.co/sy7RcNz/IMG-7089.jpg',
    price: 396,
    length: 1490,
    width: 760,
    height: 670,
    type: 'Dining',
    shape: 'Rectangular',
    color: ['White', 'Wood'],
  },
  {
    category: 'table',
    name: 'Hunter',
    fullName: 'Hunter reclaimed teak dining table',
    productInfo:
      'It’s made with hearty and thick reclaimed teak wood. It’s substantial, rich and luxurious making it strong and gorgeous as well. The teak is smoothed out and beautifully crafted, but left unfinished so that it will age over time if left unfinished.',
    img: 'https://i.ibb.co/H2Bb7KJ/IMG-7088.jpg',
    price: 2179,
    length: 2400,
    width: 1000,
    height: 760,
    type: 'Dining',
    shape: 'Rectangular',
    color: ['Wood'],
  },
  {
    category: 'table',
    name: 'Viendi',
    fullName: 'Dining table Viendi',
    productInfo:
      'The Loft style table is made of solid oak and metal. The tabletop is covered with oil and wax in 2 layers, the base - with paint in 2 layers.',
    img: 'https://i.ibb.co/QFMTgBn/IMG-7087.jpg',
    price: 429,
    length: 1510,
    width: 820,
    height: 750,
    type: 'Dining',
    shape: 'Rectangular',
    color: ['Wood'],
  },
  {
    category: 'table',
    name: 'Halmar',
    fullName: 'Dining table Halmar',
    productInfo:
      'The Halmar style is ideal for open spaces in the air and in the distance, decorated in a contemporary style.',
    img: 'https://i.ibb.co/vVMHPVS/IMG-7086.jpg',
    price: 689,
    length: 1600,
    width: 900,
    height: 750,
    type: 'Dining',
    shape: 'Rectangular',
    color: ['Wood'],
  },
  {
    category: 'table',
    name: 'Skala',
    fullName: 'Dining table Skala',
    productInfo:
      'Dining table in light walnut solid wood. Without frills and frills, but at the same time with special sophistication and waywardness. The simple standard shape, wooden top and legs make it functional and eco-friendly. Clear leg fastenings, a wide tabletop with slightly rounded edges make it possible to comfortably place at the table both a noisy group of friends and a whole group of business partners for an important meeting.',
    img: 'https://i.ibb.co/QfKgGN0/IMG-7085.jpg',
    price: 1629,
    length: 1600,
    width: 800,
    height: 750,
    type: 'Dining',
    shape: 'Rectangular',
    color: ['Wood'],
  },
  {
    category: 'table',
    name: 'Elysees',
    fullName: 'Elysees round dining table',
    productInfo:
      'The unique silhouette of the Elysees dining table will add interest to any interior.',
    img: 'https://i.ibb.co/wwCTx2m/IMG-7084.jpg',
    price: 379,
    length: 900,
    width: 900,
    height: 750,
    type: 'Dining',
    shape: 'Rounded',
    color: ['Wood'],
  },
];
